default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'postgres' %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>

development:
  <<: *default
  database: rodauth_poc__development

test:
  <<: *default
  database: rodauth_poc__test

production:
  <<: *default
  database: rodauth_poc_db
  url: <%= ENV['DATABASE_URL'] %>

